### ISSUE TITLE
Add python3 support

### ISSUE THREAD

**Issue by zebuline** [peopledoc/django-generic-filters#49]
cf https://github.com/novafloss/django-generic-filters/blob/master/tox.ini#L7

**Comment by tmartinfr** [comment]
@aRkadeFR Maybe I'll ask for your help :-) Do you already know the status of this package regarding Python 3 support ?

**Comment by aRkadeFR** [comment]
@tmartinfr no idea on the status. No problem for helping you.

**Comment by Natim** [comment]
The current status is #40 however I think we can do better.
@aRkadeFR could you activate travis on this repository? It would help to validate the status of the Py3 support.

**Comment by aRkadeFR** [comment]
@tmartinfr / @Natim already activated on the repository ? https://travis-ci.org/novafloss/django-generic-filters

**Comment by Natim** [comment]
Ok then I guess we should somehown rebase PR #40 to have travis run on it

**Comment by jayvdb** [comment]
Need to replace `bunch`, which is a dead project.  Perhaps https://pypi.org/project/Box ?

**Comment by ewjoachim** [comment]
Hi @jayvdb !

I'm not exactly sure of what you're requesting here: support for Python3 has been added in #53 (we should have closed this ticket, sorry about that)

So is it a new issue you're raising ? Can you open a new issue, and be more specific on what doesn't work anymore ?

Also your link to `https://pypi.org/project/box/` leads to a 404.

I'll be happy to help you and fix whatever needs to be fixed, but in order to make sure I fix the thing that is blocking you, I need to understand what's blocking you :)

You're right in that bunch hasn't seen any update in 9 years, but the code is not very complex, and it is python3 aware, so it's completely possible that it's still fine :) Except if you have came upon anything that bronke, in which case, again, we'll be happy to fix :)
